package org.tec_hub.tecuniversalcomm;

import android.app.Activity;
import android.os.Bundle;
import android.widget.FrameLayout;

import org.tec_hub.tecuniversalcomm.views.JoystickControl;
import org.tec_hub.tecuniversalcomm.views.TECControlView;

/**
 * Created by Nick Mosher on 5/7/15.
 * This Activity is the main screen of the user's control interface.
 * This is where users configure UI elements to act as different
 * types of remote controls.  The user will be able to create new
 * layouts for control configurations by dragging and dropping views.
 * Each view will have one or more types of data generated by it,
 * e.g. a Joystick would generate X and Y components or a button
 * would generate a true or false value.  Each piece of data can have
 * a "key" or name associated with it, which correlates to the key of
 * the JSON packet for that data when it's sent to the remote device.
 * This allows users to, for example, name the Y axis of a Joystick
 * view and retrieve that value on the remote device by parsing JSON
 * for that name.
 */
public class ControllerActivity extends Activity {

    private FrameLayout mBase;
    private TECControlView mControlView;

    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_controller);

        mBase = (FrameLayout) findViewById(R.id.controller_frame);
        mControlView = new TECControlView(this);

        JoystickControl joystick = new JoystickControl(this, "Joystick code!");
        mControlView.addChild(joystick);

        mBase.addView(mControlView);
    }
}
